### PR TITLE
add iheap and iheap2 for comparison. Not intended for an actual PR.

### PR DESCRIPTION
**Pull request by Metaxal**
This is a follow up on #14 to compare to potential approaches on making `heap-remove!` efficient by tracking indices.

We compare 2 approaches to indexed heaps.

The first one (iheap) uses internal structs that are only exposed opaquely to the user. The second one (iheap2) exposes indices.

Exposing the indices (opaquely or not) is necessary for efficiency[*].

A stress test is also included (results below). Summary of the results:
* iheap2 is faster than iheap for large heaps. It also uses 4x-8x less memory (see 'memory-use' after '*** Add elements').
* iheap is faster than iheap2 for small(ish) heaps, which I think is because of contract checking on `set-index!`. iheap doesn't have this cost because the struct definition is inside the same module.
* Currently, the interface of iheap2 is much nicer when adding elements, but this could be remedied in iheap by having also a `#:set-index!` argument to `heap-add-all!`.

```
N=1000

* iheap (opaque)
*** Add elements
cpu time: 1 real time: 1 gc time: 0
memory use: 347872
*** Remove elements
cpu time: 1 real time: 1 gc time: 0
memory use: 183216

* iheap2 (visible indices)
*** Add elements
cpu time: 2 real time: 2 gc time: 0
memory use: 61392
*** Remove elements
cpu time: 2 real time: 3 gc time: 0
memory use: 199424


N=100000

* iheap (opaque)
*** Add elements
cpu time: 37 real time: 37 gc time: 0
memory use: 30957680
*** Remove elements
cpu time: 152 real time: 152 gc time: 0
memory use: 16730720

* iheap2 (visible indices)
*** Add elements
cpu time: 58 real time: 59 gc time: 0
memory use: 3697416
*** Remove elements
cpu time: 240 real time: 240 gc time: 0
memory use: 16730720


N=1000000

* iheap (opaque)
*** Add elements
cpu time: 969 real time: 969 gc time: 551
memory use: 201112912
*** Remove elements
cpu time: 3271 real time: 3268 gc time: 242
memory use: 62312088

* iheap2 (visible indices)
*** Add elements
cpu time: 605 real time: 604 gc time: 0
memory use: 32777480
*** Remove elements
cpu time: 3615 real time: 3612 gc time: 167
memory use: 62312080

N=10000000

* iheap (opaque)
*** Add elements
cpu time: 12822 real time: 12811 gc time: 8391
memory use: 2142454872
*** Remove elements
cpu time: 75277 real time: 75199 gc time: 19805
memory use: 724454728

* iheap2 (visible indices)
*** Add elements
cpu time: 6572 real time: 6567 gc time: 380
memory use: 428437624
*** Remove elements
cpu time: 67517 real time: 67461 gc time: 14699
memory use: 724454480
```

[*] One could use a hash to track indices, but that would introduce another log *factor*, because `hash-ref` would be called at each iteration of `heapify-up/down`.

### CODE REVIEW

**Comment by Metaxal** [comment]
The memory numbers are likely not very accurate though, in particular because of the intermediate lists created by iheap when adding elements (as I said above, this could be removed with a `#:set-index` argument to `add-all!`).

**Comment by Metaxal** [comment]
Using `#:set-node!` in `heap-add-all!` for iheap, the interface is indeed nicer:
```racket
(time+memory
       (iheap-add-all! h1 elts #:set-node! set-element-h1-node!)
       (iheap-add-all! h2 elts #:set-node! set-element-h2-node!))
```
(`#:set-node!` could/should also be an argument of `make-heap`, to avoid passing it on each `heap-add!`)
The results are better for iheap, but it still uses 2x-4x more memory and is still slower on large sets.

```
N=1000

* iheap (opaque)
*** Add elements
cpu time: 1 real time: 1 gc time: 0
memory use: 158880
*** Remove elements
cpu time: 1 real time: 1 gc time: 0
memory use: 183376

* iheap2 (visible indices)
*** Add elements
cpu time: 1 real time: 1 gc time: 0
memory use: 61720
*** Remove elements
cpu time: 2 real time: 2 gc time: 0
memory use: 198944


N=100000

* iheap (opaque)
*** Add elements
cpu time: 35 real time: 35 gc time: 0
memory use: 11711808
*** Remove elements
cpu time: 153 real time: 152 gc time: 0
memory use: 16730720

* iheap2 (visible indices)
*** Add elements
cpu time: 60 real time: 60 gc time: 0
memory use: 3697416
*** Remove elements
cpu time: 247 real time: 247 gc time: 0
memory use: 16730720


N=1000000

* iheap (opaque)
*** Add elements
cpu time: 544 real time: 543 gc time: 162
memory use: 112793408
*** Remove elements
cpu time: 3300 real time: 3297 gc time: 245
memory use: 62313240

* iheap2 (visible indices)
*** Add elements
cpu time: 598 real time: 597 gc time: 0
memory use: 32777480
*** Remove elements
cpu time: 3578 real time: 3574 gc time: 166
memory use: 62312080


N=10000000

* iheap (opaque)
*** Add elements
cpu time: 9762 real time: 9756 gc time: 5707
memory use: 1148482552
*** Remove elements
cpu time: 80589 real time: 80508 gc time: 22986
memory use: 724454248

* iheap2 (visible indices)
*** Add elements
cpu time: 6718 real time: 6712 gc time: 397
memory use: 428436184
*** Remove elements
cpu time: 66961 real time: 66908 gc time: 14628
memory use: 724454480
```

**Comment by Metaxal** [comment]
An attempt to use unsafe ops for iheap2:
```racket
(define (idx1-set! elt idx)
   (unsafe-struct*-set! elt 1 idx))
(define h1 (make-iheap2 (lambda (e1 e2) (< (element-val e1) (element-val e2)))
                              #:set-index! idx1-set!
                              #:get-index element-h1-idx))
; same for h2
```
utterly failed:
```
 N=10000000

* iheap (opaque)
*** Add elements
cpu time: 10062 real time: 10057 gc time: 5879
*** Remove elements
cpu time: 81537 real time: 81475 gc time: 23588

* iheap2 (visible indices)
*** Add elements
cpu time: 23349 real time: 23345 gc time: 14573
*** Remove elements
cpu time: 443647 real time: 443415 gc time: 275756
``` 
With unsafe-ops iheap2 is almost 7x slower than with safe ops?? (and the GC blows up, too)

**Comment by Metaxal** [comment]
@rfindler @samth @rmculpepper 
So, which do you prefer? Or do you need more info?

**Comment by Metaxal** [comment]
Ping?

**Comment by rmculpepper** [comment]
I just pushed a version that uses a hash table to track indexes, but delays the initialization of the hash until the first index request. This version seems to be consistently faster, but it has a higher reported memory use. (I've only tested on Racket BC, not on CS.)

The hash version would have problems with duplicate elements, but so would iheap2. It would be possible to add a little code to detect that situation and complain. I think it would be possible to handle duplicates, but the code would be more complicated and probably slower.

The hash version supports hash-copy, which is tricky for the other two.

**Comment by Metaxal** [comment]
Thanks @rmculpepper !

Also tried Racket BC, on HEAD. I will need to try on CS before settling on any variant.

The delayed get-index is a very good idea. But this is also the main reason for the speed-up: the second heap does not need to maintain indices, saving half of the time. It's not a very likely use case when using two heaps though, but it's still a good idea in particular with a single heap.

I added a test where we force an early `get-index` for iheap3 for both heaps. It's still non-negligibly faster than iheap2.

Which makes me quite confused indeed:
1. Why would using a hash table in O(log n) read/write access be faster than using a simple struct access in O(1)?? 
2. Is it related to how using unsafe struct ops makes things much worse? (also, why?)
3. You use a hasheq for keeping references. I thought it should be hasheqv for numbers, so why does it work? [Though I think hasheq on structs will be the common, if not only, case.]
4. Regarding duplicate elements, you probably mean iheap and not iheap2?

(I'm not sure how reliable the reported memory use is but it's reasonable to assume that a hash uses a little more than structs fields.)

```
N=10000000

* iheap (opaque)
*** Add elements
cpu time: 13516 real time: 13507 gc time: 9166
memory use: 2111671760
*** Remove elements
cpu time: 74424 real time: 74353 gc time: 19435
memory use: 724454248

* iheap2 (visible indices)
*** Add elements
cpu time: 6538 real time: 6533 gc time: 384
memory use: 428437384
*** Remove elements
cpu time: 66073 real time: 66023 gc time: 14216
memory use: 724454960

* iheap3 (internal hash table)
*** Add elements
cpu time: 2227 real time: 2226 gc time: 161
memory use: 428438344
*** Remove elements
cpu time: 41617 real time: 41585 gc time: 10612
memory use: 1244548608

* iheap3 with early get-index
*** Add elements
cpu time: 5067 real time: 5063 gc time: 1513
memory use: 1468658936
*** Remove elements
cpu time: 54849 real time: 54809 gc time: 16034
memory use: 724454480

* iheap3 w/o wrapper
*** Add elements
cpu time: 1992 real time: 1990 gc time: 98
memory use: 428440744
*** Remove elements
cpu time: 34021 real time: 33997 gc time: 11524
memory use: 994153936
```

**Comment by rmculpepper** [comment]
1. Hash read and write are O(1) for a mutable hash table, which just uses a classic hashcode-indexed array. They're only O(log n) for an immutable hash table, which uses trees. (Plus the cost of computing the hashcode and comparing keys, which can be nontrivial for `equal?`-based hashes.)

2. I don't have any ideas about why unsafe ops would cause a slowdown, sorry.

3. Yes, a hasheqv might make more sense. I thought about that, but since you already had an `eq?` check on removal, I just left it alone for now. I also thought about calling `remove-duplicates` in the test setup, but I think most test runs just get lucky and don't generate any duplicates. It might make sense to let the user pick the hash type.

4. I think both would have problems, but for iheap2 it would be disastrous, because if two heaps were calling the same set-index! function, the updates would overwrite each other, and one heap might fetch the element's index in the other heap.

**Comment by Metaxal** [comment]
1. Indeed, but that doesn't explain the difference. Moreover, I wonder how lucky the hash version might be in the current case, due to structs being allocated one after the other and thus may have slowly increasing hashcodes. Hard to say though.

Anyway, it appears the real reason for the slowdown of iheap2 compared to the internal hash is module boundaries. Indeed iheap2 can also be used with a hash:
```racket
    (define h1h (make-hasheq))
    (define h2h (make-hasheq))
    (struct element (val)
      #:transparent)
    (define h1 (make-iheap2 (lambda (e1 e2) (< (element-val e1) (element-val e2)))
                            #:set-index! (λ (obj idx) (hash-set! h1h obj idx))
                            #:get-index (λ (obj) (hash-ref h1h obj))))
    (define h2 (make-iheap2 (lambda (e1 e2) (> (element-val e1) (element-val e2)))
                            #:set-index! (λ (obj idx) (hash-set! h2h obj idx))
                            #:get-index (λ (obj) (hash-ref h2h obj))))
```
and this is a lot slower as with a struct:
```
* iheap2 (visible indices)
*** Add elements
cpu time: 6349 real time: 6343 gc time: 368
memory use: 428436424
*** Remove elements
cpu time: 66470 real time: 66417 gc time: 14404
memory use: 724454480

* iheap2 +hash [NEW]
*** Add elements
cpu time: 34457 real time: 34440 gc time: 24635
memory use: 814349416
*** Remove elements
cpu time: 301797 real time: 301676 gc time: 207429
memory use: 729084776

* iheap3 (internal hash table)
*** Add elements
cpu time: 2286 real time: 2284 gc time: 166
memory use: 428438344
*** Remove elements
cpu time: 42370 real time: 42341 gc time: 10876
memory use: 1244550528

* iheap3 with early get-index
*** Add elements
cpu time: 5199 real time: 5195 gc time: 1567
memory use: 1468659896
*** Remove elements
cpu time: 56387 real time: 56345 gc time: 16683
memory use: 724452560
```
The difference is huge! And it's almost all unnecessary GC, which seems wrong. Do you know to what it may be due? 

4. I see. I was assuming that the user would take care of using different getters and setters.

**Comment by Metaxal** [comment]
In any case, your hash variant is the current best on several accounts, but I'm a little worried that the performance of the hash may crash for some weird reason, as in iheap2 + hash.

So if we could clear why iheap2 +  hash is so slow (is there a way to make it faster?) that would put my mind at ease.

**Comment by Metaxal** [comment]
I just tried on Racket CS, the results are a little different. Results are a little better for all trials, except for iheap3 with early get-index:
```
N=10000000

* iheap (opaque)
*** Add elements
cpu time: 8705 real time: 8705 gc time: 5625
memory use: 1219271416
*** Remove elements
cpu time: 40079 real time: 40080 gc time: 7306
memory use: 91102288

* iheap2 (visible indices)
*** Add elements
cpu time: 5941 real time: 5941 gc time: 834
memory use: 1999936
*** Remove elements
cpu time: 58430 real time: 58432 gc time: 20404
memory use: 137039728

* iheap2 +hash
*** Add elements
cpu time: 14988 real time: 14989 gc time: 5566
memory use: 1190737152
*** Remove elements
cpu time: 135920 real time: 135925 gc time: 30711
memory use: -42103840

* iheap3 (internal hash table)
*** Add elements
cpu time: 2202 real time: 2202 gc time: 328
memory use: 214687440
*** Remove elements
cpu time: 38853 real time: 38853 gc time: 11639
memory use: 885219104

* iheap3 with early get-index
*** Add elements
cpu time: 9563 real time: 9563 gc time: 5115
memory use: 1153858384
*** Remove elements
cpu time: 80165 real time: 80167 gc time: 10330
memory use: 129290608
```
(I removed no-wrapper from the results because it's not comparable.)

The results of iheap2 + hash are also more reasonable, and probably the overhead is due to the lambda getters and setters.

I'm now leaning toward iheap, although I'm not sure why iheap2 has so much GC, since it allocates fewer structs than iheap :thinking: 

What do you think?

**Comment by Metaxal** [comment]
(Tangentially, I just tried running this with places, and each method takes 6x more time, not counting initialization and communication. It's even worse on Racket CS :confused: Is that normal?)

**Comment by rmculpepper** [comment]
The iheap2+hash is slower because of the contracts on the set-index! and get-index functions and because it tracks indexes from the beginning rather than delaying index tracking until the first call to remove. If I change the contracts on those arguments to simply `procedure?` and if I change iheap3 to create its hash eagerly, then they perform comparably. Actually, iheap2+hash is a bit faster, but that's because it doesn't remove hash table entries, so it doesn't pay the cost of shrinking the table. That's a bug in iheap2+hash, because it prevents removed elements from being GC'd for as long as the heap is still reachable.

On Racket CS, mutable hashes seem to be slower. I'm not sure why, or whether that is likely to change.

I think iheap3 is still a better choice, because it places the fewest burdens on the client. Another possibility is to make (delayed) iheap3 the default behavior, but to have an alternative constructor that selects the iheap2 behavior, and dynamically switch between them.

**Comment by mfelleisen** [comment]
@rmculpepper @mflatt Perhaps it's worth turning the mutable hash tables into a benchmark for Matthew

**Comment by Metaxal** [comment]
Thanks for your quick and clear answer.

1. Yes, the interface for iheap3 is cleaner/nicer, which is an important point.
2. I was comparing the removal times, not the insertion times, because one usually needs 2 priority queues to remove-min! from one and remove! from the other, in alternance, defeating the purpose of delayed set-index!. In this case iheap3 with eager set-index! is twice as slow as iheap. 
3. I think all 3 algorithms can be made to use delayed set-index!.
4. For insertion times though, I don't understand why the contracts on set!-index and get-index should play any role—aren't they checked only once, on the call to `make-iheap2`?
5. Well spotted for iheap2+hash. For both iheap2+hash and iheap3, wouldn't a weak hasheq be better? Using a weak hasheq for iheap2+hash doesn't have a significant impact on the numbers.

**Comment by rmculpepper** [comment]
@mfelleisen @mflatt Sure, if Matthew is interested. I already have a self-contained version with just the hash-based heap implementation.

@Metaxal 
2. I'm not sure about the "usually", but in any case, in this benchmark, only one of the heaps needs index tracking---h1 never needs indexes, because it only gets called with `remove-min!`. The iheap2+hash version is slower than iheap3 partly because it tracks indexes for *both* heaps.
3. Yes, I think you're right.
4. No, the contracts create wrapper functions, and the heap implementation calls those wrapper functions. The wrapper for `set-index!`, for example, checks that the index argument is a number or false, and it checks that the wrapped function returns a single value.
5. A weak-hash would prevent the heap's hash from shrinking if the elements survived after being removed.

**Comment by Metaxal** [comment]
2. I updated the stress test to be closer to what I wanted to test initially, where the heaps alternate on removal (to be even closer, insertions should also be interleaved with removals).  The previous test is commented out, so still available, because it may still be informative in particular for single heaps.

4. Oh but of course! I replaced the wrappers with `procedure-arity-includes/c`. There are significant differences in the CS vs BC results (see below).
In particular, iheap2+struct is now 3x faster than iheap3 on CS, but on par on BC (and 1.5x slower than on CS).

5. Good point.

Overall, I'm quite keen on the simplicity of iheap3, but the performance on CS is a little underwhelming.

```
#### Racket CS ####

N=10000000

* iheap (opaque)
*** Add elements
cpu time: 8282 real time: 8282 gc time: 5176
memory use: 1176571272
*** Remove elements
cpu time: 39363 real time: 39364 gc time: 8431
memory use: -61658832

* iheap2 (visible indices)
*** Add elements
cpu time: 2249 real time: 2250 gc time: 322
memory use: 80003536
*** Remove elements
cpu time: 30541 real time: 30543 gc time: 10581
memory use: -16295856

* iheap2 +hash
*** Add elements
cpu time: 9084 real time: 9084 gc time: 4842
memory use: 1151307416
*** Remove elements
cpu time: 100397 real time: 100400 gc time: 19488
memory use: -335560512

* iheap3 (internal hash table)
*** Add elements
cpu time: 2118 real time: 2118 gc time: 342
memory use: 80040624
*** Remove elements
cpu time: 93580 real time: 93581 gc time: 18888
memory use: 1492097744

* iheap3 w/o wrapper
*** Add elements
cpu time: 1947 real time: 1947 gc time: 533
memory use: 349075424
*** Remove elements
cpu time: 76519 real time: 76521 gc time: 14579
memory use: 1765571464


#### Racket BC ####

N=10000000

* iheap (opaque)
*** Add elements
cpu time: 12196 real time: 12187 gc time: 7964
memory use: 2142456632
*** Remove elements
cpu time: 76119 real time: 76048 gc time: 21172
memory use: 364220224

* iheap2 (visible indices)
*** Add elements
cpu time: 3053 real time: 3050 gc time: 392
memory use: 428439304
*** Remove elements
cpu time: 51133 real time: 51092 gc time: 13708
memory use: 406861984

* iheap2 +hash
*** Add elements
cpu time: 15321 real time: 15314 gc time: 9522
memory use: 2506904144
*** Remove elements
cpu time: 103866 real time: 103772 gc time: 19548
memory use: 406861744

* iheap3 (internal hash table)
*** Add elements
cpu time: 2211 real time: 2209 gc time: 160
memory use: 428437624
*** Remove elements
cpu time: 58630 real time: 58586 gc time: 17305
memory use: 472770976

* iheap3 w/o wrapper
*** Add elements
cpu time: 2024 real time: 2022 gc time: 98
memory use: 428442664
*** Remove elements
cpu time: 60048 real time: 60007 gc time: 19615
memory use: 942520104
```

**Comment by Metaxal** [comment]
Note that the new code checks fairness but not correctness: it checks that all methods return the same value, but doesn't check that the value is correct (we can't use `sort` anymore).

**Comment by Metaxal** [comment]
Added a stress test for a single queue.
There's no significant difference between data/heap and iheap3, on both CS and BC, except that this time heaps are faster on CS.
BC:
```
N = 10000000

*** make-heap
 add:    cpu time: 8643 real time: 8635 gc time: 981
 remove: cpu time: 12453 real time: 12443 gc time: 2148

*** make-iheap3
 add:    cpu time: 9440 real time: 9432 gc time: 934
 remove: cpu time: 12616 real time: 12606 gc time: 2057
```
CS:
```
N = 10000000

*** make-heap
 add:    cpu time: 5241 real time: 5241 gc time: 275
 remove: cpu time: 3962 real time: 3962 gc time: 568

*** make-iheap3
 add:    cpu time: 5767 real time: 5767 gc time: 509
 remove: cpu time: 3781 real time: 3781 gc time: 455
```

1. I'm sad to see a factor 3 go away for CS, but given that the hash-based interface integrates very nicely with the rest, I think it remains the best option for a library.
2. Personally, I would rather not have a separate iheap implementation that does exactly the same thing plus a little more, and I would just replace data/heap with the new implementation.

@rmculpepper @rfindler @samth Are you okay with 1. and 2. above? 
If so, I'll make a new PR (sometime), unless @rmculpepper already has everything ready to push.


Thank you all for your help and your time.

**Comment by samth** [comment]
I'm also definitely in favor of keeping one heap that just has better performance for these operations.

**Comment by rmculpepper** [comment]
Yes, I agree.  I do not have anything ready to push, so please go ahead and create a new PR when you have time. Thanks!

If we keep the current behavior of iheap3, the docs should warn users that inserting duplicate elements into the heap MAY cause heap-remove! to fail to find those elements. (So users shouldn't do that.)

**Comment by Metaxal** [comment]
Ok, will do.

How about a new `heap-remove-eq!` with this caveat, while keeping the old `heap-remove!` around based on `heap-get-index` and the more generale `same?` test?

Should I include the stress test somewhere? If so, I suppose it should be excluded from the test suite?

**Pull request closed without merging**
